const ME_QUERY = 'ME_QUERY';
const AVATAR_QUERY = 'AVATAR_QUERY';
const SINGLE_UNIT_QUERY = 'SINGLE_UNIT_QUERY';
const UNITS_QUERY = 'UNITS_QUERY';

const GALLERY_IMAGE_QUERY = 'GALLERY_IMAGE_QUERY';

const COMMON_ASSET_QUERY = 'IMAGE_ASSET_QUERY';

export {
  ME_QUERY,
  AVATAR_QUERY,
  UNITS_QUERY,
  SINGLE_UNIT_QUERY,
  //
  GALLERY_IMAGE_QUERY,
  COMMON_ASSET_QUERY,
};
