import './configs/i18n.config';

import React from 'react';
import { createRoot } from 'react-dom/client';
import { RouterProvider } from 'react-router-dom';

import { AppBotnameProvider } from './providers/AppBotnameProvider';
import { QueryClientProvider } from './providers/QueryClientProvider';
// TODO: resolve chakra autogenerated features paths
import { Provider as ChakraProvider } from './features/chakra/provider';

import { appRouter } from './app';
import './index.css';

const appContainer = document.querySelector('#root[data-bubbles]') as Element;
const reactRoot = createRoot(appContainer);

reactRoot.render(
  <QueryClientProvider>
    <ChakraProvider>
      <AppBotnameProvider>
        <RouterProvider router={appRouter} fallbackElement={<div>Loading...</div>} />
      </AppBotnameProvider>
    </ChakraProvider>
  </QueryClientProvider>,
);
